# Generated by Django 2.2.6 on 2019-10-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novelrecorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='description',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='novel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='relationship',
            options={'ordering': ['character1', 'character2']},
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('novel', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='novel',
            unique_together={('author', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('character1', 'character2')},
        ),
    ]
