# Generated by Django 2.2.6 on 2019-10-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novelrecorder', '0002_auto_20191013_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
