# Generated by Django 2.2.6 on 2019-10-13 14:22
# Manual database update by YD

from django.db import migrations

from novelrecorder.models import Description


class Migration(migrations.Migration):

    dependencies = [
        ('novelrecorder', '0003_description_is_primary'),
    ]

    def updateDescriptionIsPrimary(apps, schema_editor):
        for description in Description.objects.all():
            if description.default_is_primary():
                description.is_primary = True
                description.save()


    operations = [
        migrations.RunPython(updateDescriptionIsPrimary),
    ]

